# Generated by Django 4.1.7 on 2023-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
