# Generated by Django 4.1.7 on 2023-02-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dives', '0002_rename_divelog_dives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dives',
            old_name='discription',
            new_name='description',
        ),
    ]
